### ISSUE TITLE
Can not work with Realm

### ISSUE THREAD

**Issue by zs1973** [hotchemi/PermissionsDispatcher#219] opened 2016-11-20 02:03 UTC
work with realm will lead to can not  generate xxxxxPermissionsDispatcher .

**Comment by shiraji** [comment] 2016-11-20 02:10
Why do you think Realm affect PermissionsDispatcher?

**Comment by hotchemi** [comment] 2016-11-20 11:14
@zs1973 Can you give us more info or sample project to reproduce?

**Comment by hotchemi** [comment] 2016-11-21 15:22
@zs1973 We don't have enough info to investigate more so let me close this. Please reopen if you're still struggling with(and give us more info).

**Closed** 2016-11-21 15:21 UTC
Labels: question

**Comment by akak19193** [comment] 2017-10-06 21:20
I experience the same problem. But when I open a new project and use both realm and permission dispatch it works fine.
My project level gradle looks like this:
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        // sdk and tools
        minSdkVersion = 16
        targetSdkVersion = 25
        compileSdkVersion = 25
        buildToolsVersion = '25.0.2'

        // dependencies versions
        supportLibraryVersion = '25.3.1'
        playServicesVersion = '11.0.4'
        kotlinVersion = "1.1.51"
        permissionDispatcherVersion = "3.0.1"
    }
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "io.realm:realm-gradle-plugin:4.0.0-RC1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://raw.githubusercontent.com/layerhq/releases-android/master/releases/" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
My app level gradle file looks like this:
```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()
    }

    dependencies {
        //noinspection GradleDynamicVersion
        classpath 'io.fabric.tools:gradle:1.23.0'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'realm-android'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    defaultConfig {
        applicationId "myApplicationId"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode xxx
        versionName 'x.x.x'
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            lintOptions {
                disable 'MissingTranslation'
            }
        }
        debug {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            lintOptions {
                disable 'MissingTranslation'
            }
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/rxjava.properties'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}
repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
    maven { url "https://clojars.org/repo/" }
    maven { url 'http://sdk.uxcam.com/android/' }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':layer-atlas')
    compile project(':MaterialCalendarView')
    compile "com.android.support:appcompat-v7:$rootProject.supportLibraryVersion"
    compile "com.android.support:customtabs:$rootProject.supportLibraryVersion"
    compile "com.android.support:design:$rootProject.supportLibraryVersion"
    compile "com.android.support:recyclerview-v7:$rootProject.supportLibraryVersion"
    compile "com.android.support:cardview-v7:$rootProject.supportLibraryVersion"
    compile "com.android.support:support-v4:$rootProject.supportLibraryVersion"
    compile "com.google.android.gms:play-services-gcm:$rootProject.playServicesVersion"
    compile "com.google.android.gms:play-services-location:$rootProject.playServicesVersion"
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
    compile('com.twitter.sdk.android:tweet-composer:2.3.1@aar') {
        transitive = true;
        exclude module: 'picasso'
    }
    //noinspection GradleDynamicVersion
    compile('io.branch.sdk.android:library:2.12.1') {
        exclude module: 'answers-shim'
    }
    compile('com.mikepenz:materialdrawer:5.9.2@aar') {
        transitive = true
    }
    compile "org.jetbrains.kotlin:kotlin-stdlib:$rootProject.kotlinVersion"
    compile 'com.mixpanel.android:mixpanel-android:5.1.2'
    compile 'org.slf4j:slf4j-nop:1.7.21'
    compile 'com.google.code.gson:gson:2.8.1'
    compile 'com.soundcloud.android:android-crop:1.0.1@aar'
    compile 'com.alexvasilkov:gesture-views:2.3.1'
    compile 'com.github.jkwiecien:EasyImage:1.3.1'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'commons-io:commons-io:2.5'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.layer.sdk:layer-sdk:0.21.3'
    compile 'com.github.bumptech.glide:glide:3.8.0'
    compile 'com.github.bumptech.glide:okhttp3-integration:1.5.0@aar'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'
    compile 'com.wang.avi:library:2.1.3'
    compile 'com.github.d-max:spots-dialog:0.7@aar'
    compile 'com.afollestad.material-dialogs:core:0.9.4.5'
    compile 'org.apache.commons:commons-lang3:3.5'
    compile 'com.miguelcatalan:materialsearchview:1.4.0'
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.8'
    compile 'com.github.zookey:universalpreferences:0.0.4'
    compile 'com.jakewharton:butterknife:8.8.1'
    compile 'com.flyco.tablayout:FlycoTabLayout_Lib:2.1.2@aar'
    compile 'com.ogaclejapan.smarttablayout:library:1.6.1@aar'
    compile 'com.ogaclejapan.smarttablayout:utils-v4:1.6.1@aar'
    compile 'it.sephiroth.android.library.targettooltip:target-tooltip-library:1.3.15'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'org.zakariya.stickyheaders:stickyheaders:0.7.6'
    compile 'com.jakewharton.timber:timber:4.5.1'
    compile 'com.getbase:floatingactionbutton:1.10.1'
    compile 'com.google.guava:guava:20.0'
    compile 'com.daimajia.swipelayout:library:1.2.0@aar'
    compile 'io.reactivex.rxjava2:rxjava:2.1.0'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'com.github.vipulasri:timelineview:1.0.5'
    compile 'com.jakewharton.threetenabp:threetenabp:1.0.5'
    compile 'io.reactivex.rxjava2:rxkotlin:2.0.3'
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.27'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.romandanylyk:pageindicatorview:0.2.0'
    compile "com.github.hotchemi:permissionsdispatcher:$rootProject.permissionDispatcherVersion"
    annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:$rootProject.permissionDispatcherVersion"
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    compile 'cn.aigestudio.wheelpicker:WheelPicker:1.1.2'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5.1'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.1'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.1'
    compile 'com.uxcam:uxcam:2.5.10@aar'
    compile 'id.zelory:compressor:2.1.0'
}
apply plugin: 'com.google.gms.google-services'
```
And it will throw errors during compile process about cannot find symbol xxxPermissionsDispatcher, which just works fine before adding realm. Any help? Thanks!

**Comment by shiraji** [comment] 2017-10-08 13:24
Could you ask that to realm?

**Comment by akak19193** [comment] 2017-10-13 21:01
I solved this issue by reference of [this issue](https://github.com/realm/realm-java/issues/4650). Thanks anyway.
