### ISSUE TITLE
SupportV13MissingException when jack is enabled

### ISSUE THREAD

**Issue by livotov** [hotchemi/PermissionsDispatcher#220] opened 2016-11-21 09:57 UTC
After enabling the Jack, Im getting permissions.dispatcher.processor.exception.SupportV13MissingException: PermissionsDispatcher for annotated class 'MyFragment' can't be generated, because the support-v13 dependency is missing on your project
<br />
<br />The v13 dependency is in place, it works fine if I switch back to apt plugin.

**Comment by aurae** [comment] 2016-11-21 10:50
Thanks for your report! I can reproduce the issue here.

We'd have to look deeper into what classpath Jack is provided with when invoking its annotation processors, because it doesn't seem to pick up on the `support-v13` library. There's a simple `Class.forName` check to determine if that library is available (more specifically, `FragmentCompat`), so that's really the only explanation I can come up with right now, as to why this lookup fails, even though the class is available to the application.

**Comment by shiraji** [comment] 2016-11-21 12:44
@aurae Could you provide a sample project and steps to repoduce this issue?

**Comment by aurae** [comment] 2016-11-21 13:29
Sure thing, I'll prepare that shortly.

**Comment by hotchemi** [comment] 2016-11-21 15:21
Thx contributors! I'm still not sure this is our side bug since I dunno Jack will assure the classpath around behavior compatibility...I'll wait @aurae 's work:D

**Comment by livotov** [comment] 2016-11-21 17:26
Thanks guys and great it's reproducible!

btw, @hotchemi  , didn't you think to just make 2 extra modules, so one can include either one or another dependency, depending on support fragments usage, like

```
compile 'com.github.hotchemi:permissionsdispatcher:${latest.version}'
apt 'com.github.hotchemi:permissionsdispatcher-processor-support:${latest.version}'

```
or

```
compile 'com.github.hotchemi:permissionsdispatcher:${latest.version}'
apt 'com.github.hotchemi:permissionsdispatcher-processor:${latest.version}'
```

**Comment by hotchemi** [comment] 2016-11-22 05:31
@livotov Thx! What's the difference between you suggested? Do you mean like exporting support native Fragment feature as another module dependency?

**Comment by livotov** [comment] 2016-11-22 06:40
yeah, exactly, so one can simply add on or another "compile/apt" statement depending on the project. This could reduce some boilerplate if/else code in the library as well as make the library free from such classpath errors when jack or sms else will change again. Just a thought.

**Comment by aurae** [comment] 2016-11-22 08:07
Personally, I find the auto-detection route that we've been going so far to be more elegant, since it doesn't really add any unnecessary boilerplate to the logic of our annotation processor. Therefore, I'm confident that we can make this work with Jack without having to introduce yet another artifact. Fingers crossed!

**Comment by hotchemi** [comment] 2016-12-08 06:04
@aurae Can you take a look? 😃

**Comment by aurae** [comment] 2016-12-08 07:35
I'm out of the country at the moment, but it's on my backlog, yes!

**Comment by aurae** [comment] 2016-12-11 01:48
I've created a jack-based sample project [in a dedicated branch within my fork](https://github.com/aurae/PermissionsDispatcher/tree/issue220_sample) to show off the issue. Running the `sample:assemble` task completes without error, running `sample-jack:assemble` fails with the error mentioned in the OP.
Please excuse the delay. 🙇

**Comment by hotchemi** [comment] 2016-12-13 13:24
@livotov Can you check? https://github.com/hotchemi/PermissionsDispatcher/issues/220#issuecomment-266255116

**Comment by aurae** [comment] 2016-12-13 15:25
I meant that I only created a project that exposes the issue, I haven't done any work to actually fix it yet. :) I may have a time slot on the weekend open for this, however feel free to join in before that, guys!

**Comment by hotchemi** [comment] 2016-12-13 15:34
Ah sorry! Take your time @aurae 🙇

**Comment by E3V3A** [comment] 2017-01-18 08:11
Not sure if this helps, but I found this from [here](http://tools.android.com/tech-docs/jackandjill):

>  **Known issues**
>
> Instant Run does not currently work with Jack and will be disabled while using the new toolchain.
> 
> Because Jack does not generate intermediate class files when compiling an app, tools that depend on these files do not currently work with Jack. Some examples of these tools are:
>
> - Lint detectors that operate on class files
> - Tools and libraries that require the app’s class files (such as instrumentation tests with JaCoCo)
> 
> If you find other issues while using Jack, please file a bug.

**Comment by ankitbatra11** [comment] 2017-02-19 17:16
Hi, is there an update on this? This is the only blocking step in upgrading my app to Jack compiler.

**Comment by shiraji** [comment] 2017-02-20 21:41
I was thinking `Jack` is responsible for fixing this issue. However, since they don't handle this problem yet, we could provide a temporary solution like an override flag to skip the [check](https://github.com/shiraji/PermissionsDispatcher/blob/6e9d95695790ac38d256a91df3ee739f0f6196a3/processor/src/main/kotlin/permissions/dispatcher/processor/impl/NativeFragmentProcessorUnit.kt#L21-L21) which is what @aurae wrote. If `Jack` resolve this issue, I would like to remove the feature.

**Comment by hotchemi** [comment] 2017-02-21 01:43
I think the most simple solution is using v4 Fragment(Ive never used normal fragment actually).
Why do you guys use normal Fragment?

**Comment by ankitbatra11** [comment] 2017-02-21 06:03
I use PreferenceFragment that derives from android.app.Fragment in my
project.

**Comment by shiraji** [comment] 2017-02-21 06:23
How about `PreferenceFragmentCompat`?

**Comment by ankitbatra11** [comment] 2017-02-21 06:29
It's a lot of work in my project to convert to fragment compat as I have a
lot of settings screen. I would rather have this issue fixed or stay at
java 1.7.

**Comment by shiraji** [comment] 2017-03-15 05:40
Can we close this? 

https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+blogspot/hsDu+(Android+Developers+Blog)

**Comment by hotchemi** [comment] 2017-03-16 14:48
@livotov Unfortunately(or fortunately) Jack became obsoleted so we decided not to support it actively. On the other hand about implicit switching to not-v4 Fragment support I have some thoughts and will be discussing on https://github.com/hotchemi/PermissionsDispatcher/issues/254.
Thx for your report!

**Closed by hotchemi** 2017-03-16 14:48 UTC
Labels: bug, contributionwelcome
