### ISSUE TITLE
OnNeverAskAgain and OnShowRationale are never called

### ISSUE THREAD

**Issue by whenan** [hotchemi/PermissionsDispatcher#123] opened 2016-03-24 08:26 UTC
The phone is htc m8sw,os version is android 6.0.1.I use your library，but both OnNeverAskAgain and OnShowRationale are never called. Library version is 2.1.0.Help me.

**Comment by hotchemi** [comment] 2016-03-24 08:35
Please show us a sample code please? And you can look at our sample module.

**Comment by whenan** [comment] 2016-03-24 08:45
1,public void onClick(View v) {
		switch (v.getId()) {
		**case R.id.service_item3:
			MoreActivityPermissionsDispatcher.callPhoneWithCheck(this);**
 
2,@OnShowRationale(Manifest.permission.CALL_PHONE)
	void showRationaleForcallPhone(final PermissionRequest request) {
		new AlertDialog.Builder(this)
				.setTitle("提示")
				.setMessage("需要授权电话权限")
				.setNegativeButton("取消", new DialogInterface.OnClickListener() {
					@Override
					public void onClick(DialogInterface dialog, int which) {
						request.cancel();
					}
				})
				.setPositiveButton("确定", new DialogInterface.OnClickListener() {
					@Override
					public void onClick(DialogInterface dialog, int which) {
						request.proceed();
					}
				})
				.create()
				.show();
	}

	@OnPermissionDenied(Manifest.permission.CALL_PHONE)
	void showDeniedcallPhone() {
		Toast.makeText(this, "你竟拒绝了我", Toast.LENGTH_SHORT).show();
	}

	@OnNeverAskAgain(Manifest.permission.CALL_PHONE)
	void showNeverAskForcallPhone() {
		Toast.makeText(this, "你真的不爱我了？？？", Toast.LENGTH_SHORT).show();
	}

**Comment by whenan** [comment] 2016-03-24 08:52
3,
@RuntimePermissions
public class MoreActivity extends BaseActivity 

4,@Override
	public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
		super.onRequestPermissionsResult(requestCode, permissions, grantResults);
		MoreActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
	}

**Comment by hotchemi** [comment] 2016-03-24 08:56
It seems there is no @NeedsPermission annotated method.

**Comment by whenan** [comment] 2016-03-24 08:58
@NeedsPermission(Manifest.permission.CALL_PHONE)
	void callPhone() {
		 Intent intent = new Intent(Intent.ACTION_DIAL, Uri.parse("tel:4009930630"));
		 startActivity(intent);
	}

**Comment by hotchemi** [comment] 2016-03-24 09:07
Could you paste the code of MoreActivityPermissionsDispatcher? There is an answer.

**Comment by whenan** [comment] 2016-03-24 09:07
// This file was generated by PermissionsDispatcher. Do not modify!
package com.ciyun.lovehealth.setting;

import android.support.v4.app.ActivityCompat;
import java.lang.Override;
import java.lang.String;
import java.lang.ref.WeakReference;
import permissions.dispatcher.PermissionRequest;
import permissions.dispatcher.PermissionUtils;

final class MoreActivityPermissionsDispatcher {
  private static final int REQUEST_CALLPHONE = 0;

  private static final String[] PERMISSION_CALLPHONE = new String[] {"android.permission.CALL_PHONE"};

  private MoreActivityPermissionsDispatcher() {
  }

  static void callPhoneWithCheck(MoreActivity target) {
    if (PermissionUtils.hasSelfPermissions(target, PERMISSION_CALLPHONE)) {
      target.callPhone();
    } else {
      if (PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_CALLPHONE)) {
        target.showRationaleForcallPhone(new CallPhonePermissionRequest(target));
      } else {
        ActivityCompat.requestPermissions(target, PERMISSION_CALLPHONE, REQUEST_CALLPHONE);
      }
    }
  }

  static void onRequestPermissionsResult(MoreActivity target, int requestCode, int[] grantResults) {
    switch (requestCode) {
      case REQUEST_CALLPHONE:
      if (PermissionUtils.getTargetSdkVersion(target) < 23 && !PermissionUtils.hasSelfPermissions(target, PERMISSION_CALLPHONE)) {
        target.showDeniedcallPhone();
        return;
      }
      if (PermissionUtils.verifyPermissions(grantResults)) {
        target.callPhone();
      } else {
        if (!PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_CALLPHONE)) {
          target.showNeverAskForcallPhone();
        } else {
          target.showDeniedcallPhone();
        }
      }
      break;
      default:
      break;
    }
  }

  private static final class CallPhonePermissionRequest implements PermissionRequest {
    private final WeakReference<MoreActivity> weakTarget;

    private CallPhonePermissionRequest(MoreActivity target) {
      this.weakTarget = new WeakReference<>(target);
    }

    @Override
    public void proceed() {
      MoreActivity target = weakTarget.get();
      if (target == null) return;
      ActivityCompat.requestPermissions(target, PERMISSION_CALLPHONE, REQUEST_CALLPHONE);
    }

    @Override
    public void cancel() {
      MoreActivity target = weakTarget.get();
      if (target == null) return;
      target.showDeniedcallPhone();
    }
  }
}

**Comment by hotchemi** [comment] 2016-03-24 09:13
I think code is generated correctly. Any stacktrace?

**Comment by whenan** [comment] 2016-03-24 09:31
[2.txt](https://github.com/hotchemi/PermissionsDispatcher/files/187522/2.txt)

**Comment by hotchemi** [comment] 2016-03-24 09:33
Umm, sorry I can't find the cause. Could you give us a sample app?

**Comment by whenan** [comment] 2016-03-24 09:34
It is very strange, I do not know whether the htc rom cuaused the error

**Comment by whenan** [comment] 2016-03-24 10:03
Process: com.android.packageinstaller, PID: 681
                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity}: java.lang.NullPointerException: Attempt to get length of null array
                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2509)
                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569)
                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:168)
                                                   at android.app.ActivityThread.main(ActivityThread.java:5885)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                   at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.computePermissionGrantState(GrantPermissionsActivity.java:325)
                                                   at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.updateDefaultResults(GrantPermissionsActivity.java:374)
                                                   at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(GrantPermissionsActivity.java:120)
                                                   at android.app.Activity.performCreate(Activity.java:6262)
                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462)
                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569) 
                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399) 
                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                   at android.os.Looper.loop(Looper.java:168) 
                                                   at android.app.ActivityThread.main(ActivityThread.java:5885) 
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
03-24 18:02:26.713 2386-5650/? E/ActivityManager: App crashed! Process: com.android.packageinstaller

**Comment by whenan** [comment] 2016-03-24 10:06
![3](https://cloud.githubusercontent.com/assets/16183633/14014043/010dbf9a-f1eb-11e5-9f48-f2014ba1d965.png)
It seems the room has a bug.

**Comment by whenan** [comment] 2016-03-24 10:25
The Attachment is my demo.
[Permission.zip](https://github.com/hotchemi/PermissionsDispatcher/files/187617/Permission.zip)

**Comment by shiraji** [comment] 2016-03-24 11:10
Have you tried other device?

**Comment by whenan** [comment] 2016-03-25 05:15
I will try another device,thank you!

**Comment by Smeet123** [comment] 2016-03-25 07:19
@whenan You miss to write <uses-permission android:name="android.permission.CALL_PHONE"/> in your manifest file.

**Comment by hotchemi** [comment] 2016-03-25 07:35
Good catch ever!!!

**Comment by whenan** [comment] 2016-03-25 07:35
Yes,I see,but also  OnNeverAskAgain and OnShowRationale are never called

**Comment by whenan** [comment] 2016-03-25 07:39
The crash gone,but still both OnNeverAskAgain and OnShowRationale are never called

**Comment by hotchemi** [comment] 2016-03-25 07:41
Have you rebuild the project?

**Comment by whenan** [comment] 2016-03-25 07:42
even when I denied the permisson ,the NeedsPermission was callback.

**Comment by whenan** [comment] 2016-03-25 07:48
Yes,  I  rebuild the project.

**Comment by whenan** [comment] 2016-03-25 07:55
Who can help me? I'm confused

**Comment by hotchemi** [comment] 2016-03-25 08:02
I'll try to reproduce the problem tonight.
But you can quickly debug the code if you put break point on a MoreActivityPermissionsDispatcher class. Could you try that?

**Comment by whenan** [comment] 2016-03-25 08:04
OK，I will have a try.

**Comment by hotchemi** [comment] 2016-04-03 23:09
@whenan Did u solve this problem?

**Comment by whenan** [comment] 2016-04-05 09:16
Sorry,not yet,did you reproduce the problem?

**Comment by hotchemi** [comment] 2016-04-10 20:41
I couldn't reproduce the problem so I'm gonna close this issue, sorry.

**Closed by hotchemi** 2016-04-10 20:41 UTC
Labels: question

**Comment by Smeet123** [comment] 2016-04-11 06:26
Yes and @whenan, I tried your example and it is working fine with the added permission in manifast. I test the demo/example provided by you and it is working fine. Please check once again, you may did some minor mistakes. For further detail, please check my demo app : https://github.com/hotchemi/PermissionsDispatcher/files/191383/Permission.zip
