### ISSUE TITLE
Annotated method with internal modifier cause wrong kapt generation

### ISSUE THREAD

**Issue by r-ralph** [hotchemi/PermissionsDispatcher#171] opened 2016-07-11 07:28 UTC
I'm using PermissionDispatcher with kotlin and kapt. I found strange behavior in PermissionDispatcher.
Creating method annotated with `@NeedsPermission` and add `internal` modifier, then created class `***PermissionsDispatcher` looks

``` java
final class MainActivityPermissionsDispatcher {
  private static final int REQUEST_SHOWCAMERA$APP_COMPILEDEBUGKOTLIN = 0;

  private static final String[] PERMISSION_SHOWCAMERA$APP_COMPILEDEBUGKOTLIN = new String[] {"android.permission.CAMERA"};

  private MainActivityPermissionsDispatcher() {
  }

  static void showCamera$app_compileDebugKotlinWithCheck(MainActivity target) {
    if (PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWCAMERA$APP_COMPILEDEBUGKOTLIN)) {
      target.showCamera$app_compileDebugKotlin();
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_SHOWCAMERA$APP_COMPILEDEBUGKOTLIN, REQUEST_SHOWCAMERA$APP_COMPILEDEBUGKOTLIN);
    }
  }

  static void onRequestPermissionsResult(MainActivity target, int requestCode, int[] grantResults) {
    switch (requestCode) {
      case REQUEST_SHOWCAMERA$APP_COMPILEDEBUGKOTLIN:
      if (PermissionUtils.getTargetSdkVersion(target) < 23 && !PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWCAMERA$APP_COMPILEDEBUGKOTLIN)) {
        return;
      }
      if (PermissionUtils.verifyPermissions(grantResults)) {
        target.showCamera$app_compileDebugKotlin();
      }
      break;
      default:
      break;
    }
  }
}
```

Annotated method is below.

``` kotlin
@NeedsPermission(Manifest.permission.CAMERA)
internal fun showCamera() {
}
```

Generated method and variable name may be wrong and it may be bug. 
### Enviroment
- Android Studio 2.1
- Android Gradle Plugin 2.1.0
- BuildTools 23.0.3
- Kotlin 1.0.3
- PermissionsDispatcher 2.1.3

**Comment by hotchemi** [comment] 2016-07-12 15:49
@r-ralph Thx, I think this issue is caused by getting different information from annotation processor API, but I'm not sure how internal method is inlined at compile time actually...
Is it possible to deal with this issue by not adding internal for the time being?

**Comment by r-ralph** [comment] 2016-07-13 15:43
@hotchemi Thank you for the quick response. I deal with this problem in that way.

**Comment by hotchemi** [comment] 2016-12-08 06:05
I guess @jmatsu had been working on the issue...any update?

**Comment by kibotu** [comment] 2017-01-20 13:01
fun fact: when using android studio's automatic conversion from java to kotlin it adds `internal` to the annotated methods, that's presumably how people end up with this behaviour

**Comment by hotchemi** [comment] 2017-03-29 13:00
@jmatsu Any update?

**Comment by jmatsu** [comment] 2017-04-16 04:53
@hotchemi 
Sorry for delay. 🙇 

### Conclusion
Cannot use `internal` methods w/ PermissionsDispatcher.
However, PermissionsDispatcher didn't generate `wrong` code for internal methods.

According to [the official document](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#visibility), visibility of `internal` entities becomes `public` if Java code is in same [module](https://kotlinlang.org/docs/reference/visibility-modifiers.html#modules) of kotlin files.
But it seems Java code cannot access `internal` entities from even if all codes are in same module.

### Workarounds (Probably)

+ Don't use `internal` modifier.

+ Replace generated Java code with kotlin code by inserting a Java2Kotlin convert task after kapt.
We can use an official module which can convert Java to Kotlin which is [JetBrains/j2k](https://github.com/JetBrains/kotlin/tree/master/j2k).

I haven't tried 2nd workaround, so I'm not sure it's possible.
FYI, I created a project to verify this on AndroidStudio and IntelliJ with kotlin 1.0.7. https://github.com/jmatsu/internal-entity-access-from-java-sample

**Comment by hotchemi** [comment] 2017-04-17 05:33
@jmatsu Thx for your dedicated investigation!!!
well...currently we nee to follow `Don't use internal modifier.`. Actually we're able to generate Kotlin file with annotation processing but I suppose it's too much and I'm afraid it will increase the maintenance cost of developers...

And another point is that with Kotlin probably we'll be able to handle such a problem by Delegate property approach. So we're not going to proceed any step to address the problem.

@r-ralph Are you still being in trouble with this issue? Let me clarify 🙇

**Comment by r-ralph** [comment] 2017-04-17 14:40
@hotchemi I'm using without `internal` modifier now, and it works correctly. So I am not in a trouble now. Thank you for your kindness.

**Comment by hotchemi** [comment] 2017-05-12 14:39
Added to known issues page so let me close the issue.
https://github.com/hotchemi/PermissionsDispatcher/blob/master/doc/known_issues.md

**Closed by hotchemi** 2017-05-12 14:39 UTC
Labels: contributionwelcome, enhancement

**Comment by hotchemi** [comment] 2017-07-19 05:46
@r-ralph now you can test `inline` with `3.0.0-SNAPSHOT`!

**Comment by r-ralph** [comment] 2017-10-03 06:46
@hotchemi Sorry for my late reply.
I update to 3.0.1 and it works perfectly! Thanks for the update!
