### ISSUE TITLE
it not work in samsung os ,other is fine

### ISSUE THREAD

**Issue by s949492225** [hotchemi/PermissionsDispatcher#285] opened 2017-03-06 08:53 UTC
## FAQs

Before you add the issue, please make sure to read over the following Frequently Asked Questions:

**"XxxPermissionsDispatcher class is not generated"**

- Did you add `@RuntimePermissions` to your class, and `@NeedsPermission` to your method?
- Did you try a Rebuild? (Sync is not Rebuild!)
- Don't mix `apt` and `annotationProcessor`!
- If you're in Kotlin, use `kapt`!
- If you're using Realm 1.x., please consider upgrading to 2.x (refer to Issue #270: https://github.com/hotchemi/PermissionsDispatcher/issues/270)
- If you checked all these steps, and the generated classes are still not showing up, then attach your Activity/Fragment class, and build.gradle.
 
___

## Overview

- Describe the issue briefly
it not work in samsung devices ,when touch accept option , PermissionUtils.verifyPermissions(grantResults) return false ,and it always return false ,so the dialog always pop when open app.

device samsung s6
os version : android 6.0 

### Expected
work right
### Actual
PermissionUtils.verifyPermissions(grantResults) return false ,and it always return false ,so the dialog always pop when open app.

## Environment
device samsung s6
os version : android 6.0 

it is official doc :https://seap.samsung.com/content/playing-android-m-permissions-solutions-enterprises

You may be tested in a variety of devices;

## Reproducible steps
Normal use will appear

**Comment by shiraji** [comment] 2017-03-06 09:38
> attach your Activity/Fragment class, and build.gradle.

**Comment by hotchemi** [comment] 2017-03-06 11:52
@s949492225 Thx for your info. We need more info to proceed an investigation.
Could you give us a small sample that can reproduce the problem?

**Comment by s949492225** [comment] 2017-03-07 02:32
build.gradle and apt is right ,work right
just in samsung、vivo ，other device work fine,
this is the key code 

`@RuntimePermissions
public class SplashActivity extends BaseActivity {
    private long startTime;
    private SplashManager manager = new SplashManager();

    @Override
    protected int getLayoutId() {
        return R.layout.activity_bssplash;
    }

    @Override
    protected void init(Bundle savedInstanceState) {
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        if (manager.hasDownLoadSplash()) {
            mHelper.setImage(R.id.splash, manager.getSplashFile());
        }else{
            FunctorHelper.setSplashSig("need to down splash image");
        }
        SplashActivityPermissionsDispatcher.goNextWithCheck(this);
        Requestor.Account.loginStatus();
    }

    @NeedsPermission({
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS,
            Manifest.permission.READ_CONTACTS,
            Manifest.permission.CALL_PHONE})
    public void goNext() {
        startTimer();
    }

    @OnShowRationale({
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS,
            Manifest.permission.READ_CONTACTS,
            Manifest.permission.CALL_PHONE})
    void showRationale(final PermissionRequest request) {
        new AlertDialog.Builder(this)
                .setTitle("权限申请提示")
                .setMessage("熊猫美妆需要您授权一些权限才能运行某些功能,请您在接下来点击允许！")
                .setPositiveButton("知道了", (dialog, which) -> request.proceed())
                .setNegativeButton("拒绝", (dialog, which) -> request.cancel())
                .show();
    }

    @OnPermissionDenied({
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS,
            Manifest.permission.READ_CONTACTS,
            Manifest.permission.CALL_PHONE})
    void denied() {
        startTimer();
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        SplashActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        return keyCode == KeyEvent.KEYCODE_BACK || super.onKeyDown(keyCode, event);
    }

    private void startTimer() {
        startTime = System.currentTimeMillis();
        new Thread(this::sleep).start();
    }

    private void sleep() {
        try {
            long endTime = System.currentTimeMillis();
            int sleepTime = (int) (endTime - startTime);
            sleepTime = sleepTime < 3000 ? 3000 - sleepTime : 1;
            Thread.sleep(sleepTime);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        runOnUiThread(this::openMain);
    }

    private void openMain() {
        if (FunctorHelper.getGuideEnable()) {
            GuideActivity.Open(this);
        } else {
            MainActivity.Open(this);
        }
        finish();
    }
}
`

**Comment by aurae** [comment] 2017-03-07 08:20
Thanks for reporting! Your setup seems correct. Unfortunately, I don't own an S6, but we might be able to recreate the issue with another Samsung device. This actually might sound like a manufacturer-specific issue.

**Comment by s949492225** [comment] 2017-03-07 08:28
After my test, I found in other ROM also have the same problem, because the vendor modify system API led to these problems, only to fit the vendor's system, authority to manage the function is too sensitive.

**Comment by aurae** [comment] 2017-03-07 08:42
In your example, you're requesting quite a few permissions at once - maybe one of them is causing the issue on these devices? I'd suggest you remove one permission at a time from the list of requested permissions, and try again. Maybe start with `MOUNT_UNMOUNT_FILESYSTEMS`, since that's the one I'm least familiar with, and which seems to have the most impact?

**Comment by s949492225** [comment] 2017-03-07 09:05
I'll try it, thanks

**Comment by hotchemi** [comment] 2017-03-12 16:49
@s949492225 any update?

**Comment by hotchemi** [comment] 2017-03-16 14:44
@s949492225 I'll close this issue, pls open if needed.

**Closed by hotchemi** 2017-03-16 14:44 UTC
Labels: question
