### ISSUE TITLE
Processor throws IllegalArgumentException

### ISSUE THREAD

**Issue by wjwarren** [hotchemi/PermissionsDispatcher#46] opened 2015-11-26 09:42 UTC
Using version 2.0.0, I am getting the following error from the processor.

```bash
Caused by: java.lang.IllegalArgumentException: ()void
        at com.sun.tools.javac.model.JavacTypes.validateTypeNotIn(JavacTypes.java:290)
        at com.sun.tools.javac.model.JavacTypes.isSubtype(JavacTypes.java:91)
        at permissions.dispatcher.processor.util.ExtensionsKt.isSubtypeOf(Extensions.kt:67)
        at permissions.dispatcher.processor.util.ValidatorsKt.findAndValidateProcessorUnit(Validators.kt:20)
        at permissions.dispatcher.processor.PermissionsProcessor.process(PermissionsProcessor.kt:68)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java
:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1106)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:417)
```

When I force version 1.2.1 everything works fine.

I am not sure how to debug this, so if you need any more information, I am happy to provide it for you.

**Comment by aurae** [comment] 2015-11-26 10:10
The stack trace suggests that this error has been thrown because the processor couldn't verify an element annotated with `@RuntimePermissions`... which is odd, since it describes the wrong type with '()void'.

`JavacTypes#isSubtypeOf` throws an `IllegalArgumentException` if any of its two `TypeMirror` parameters are of type `EXECUTABLE` or `PACKAGE`:
```java
public boolean isSubtype(TypeMirror var1, TypeMirror var2) {
    this.validateTypeNotIn(var1, EXEC_OR_PKG);
    this.validateTypeNotIn(var2, EXEC_OR_PKG);
    return this.types.isSubtype((Type)var1, (Type)var2);
}
```

`EXECUTABLE` basically refers to methods, `PACKAGE` refers to a package's pseudo-type, neither of which you should even be allowed to annotate with PermissionsDispatcher. Even weirder that the same checks succeed on 1.2.1.

Are you using a JDK 7 environment? It could potentially cause problems with 2.0.0 since that was compiled using Java 8. I will look into this and check if that actually could be case, since that would be my primary lead at this time. Other than that, I'm not sure as to why this would be thrown.

**Comment by wjwarren** [comment] 2015-11-26 10:16
> Are you using a JDK 7 environment?

Yes. 

When I have a little more time, I'll see if I can upgrade to Java 8 without causing any issues in my project.

Thanks!

**Comment by aurae** [comment] 2015-11-26 10:17
Actually, it was a mistake compiling the library with Java 8 in the first place! I will verify that this is actually the cause of this issue and re-upload a JDK 7-compiled build.

**Comment by aurae** [comment] 2015-11-26 10:30
Okay, I have just created a vanilla project using a JDK 7 installation, and I'm able to pull in the library and process my annotated `Activity` and both flavors of `Fragment` just fine.

Could you list the classes you annotated with `@RuntimePermissions` in your project, and check if there are native Fragments (i.e. `android.app.Fragment` as opposed to the `support.v4` variant) among them? How are you defining the dependency in your `build.gradle`? Are you using any other annotation processors along with PermissionsDispatcher? I'm trying to get a better picture of the environment you're working with.

**Comment by hotchemi** [comment] 2015-11-26 10:56
Yup and we should report adequate message.

**Comment by wjwarren** [comment] 2015-11-26 10:58
All classes annotated with `@RuntimePermissions` either extend `android.support.v4.app.Fragment` or `android.support.v7.app.AppCompatActivity`.

The dependency is defined as recommended from the readme.

Other annotation processors I use are Dagger (1.2.1) and Butterknife (3.0.0).

A better error message would be nice yeah :wink:

**Comment by hotchemi** [comment] 2015-11-26 11:04
Umm it seems that we have a bug but...
@wjwarren Do u need a 2.0.0 soon? Actually 2 ver is still beta and 1.2.x is stable release.

**Comment by aurae** [comment] 2015-11-26 11:33
It's most likely unrelated to the issue, but: Any reason for ButterKnife 3.0.0? Last time I checked, it's at 7.0.1 at the moment!

The problem I have with this exception is that I don't know why the `Element` argument passed into `findAndValidateProcessorUnit()` should be resolved to '()void'. Its usage is as follows:

```java
roundEnv!!.getElementsAnnotatedWith(RuntimePermissions::class.java).forEach {
    // Find a suitable ProcessorUnit for this element
    val processorUnit = findAndValidateProcessorUnit(processorUnits, it)
    // (code generation omitted)
}
```

In this block, `it` resolves to an Element annotated with `@RuntimePermissions`, and `processorUnits` is a List of implementations for the different kinds of code generators, based on the annotated element (`Activity`, `Fragment`, `support.v4.Fragment`). PermissionsDispatcher throws a `WrongClassException` if the annotated element is of neither type, however that clearly seems to be given in this context.

I will try to reproduce this behaviour some more, however I'm at a loss right now.

**Comment by wjwarren** [comment] 2015-11-26 11:56
Thanks for the fast feedback again! I don't *need* 2.0.0 soon, but that is what Gradle gives me if I use `+` for the version in the dependency declaration. I am fine to keep using 1.2.1 for now.

As for Butterknife, I honestly don't remember why I am stuck on 3.0.0. Could be that some other dependency had a problem with a newer version. Must have completely forgotten to try and upgrade again, but as you say, it is most likely unrelated.

**Comment by hotchemi** [comment] 2015-11-26 23:07
Just realized travis ci failed.

**Comment by hotchemi** [comment] 2015-11-29 16:29
@wjwarren Have you tried to update butterknife to 8.0.0-SNAPSHOT?
Older version of butterknife includes annotation processing module at runtime jar, so it might cause unexpected problem with other annotation processing, I guess.

**Comment by wjwarren** [comment] 2015-11-30 11:43
I did try, but unfortunately ran into some issues with that. I don't have too much time to spend on that at the moment as I am swamped with other tasks.

**Comment by aurae** [comment] 2015-11-30 14:13
Fwiw, I have been using PermissionsDispatcher together with Butterknife and Dagger for a long time, and the new version didn't cause any issues with those annotation processors. Still baffled at what causes this issue for you, wjwarren.

**Comment by hotchemi** [comment] 2015-11-30 14:14
@wjwarren Could u give us a sample app?

**Comment by wjwarren** [comment] 2015-11-30 15:53
I just realised that the butterknife issues are at runtime only, so no problem testing this library with the latest butterknife version. Unfortunately I do still get the same error.

I wish I had time to dive deep into this, see what the culprit is and create a sample app, but unfortunately I don't. When things quiet down for me a little I will try and create a sample app for you.

**Comment by aurae** [comment] 2015-11-30 19:03
Awesome! In the meantime, we will try to reproduce the issue some more.

**Comment by hotchemi** [comment] 2015-12-01 01:46
OK, so I'll close this issue temporarily and please reopen something is wrong.

**Closed by hotchemi** 2015-12-01 01:46 UTC
Labels: 2.x, question
